environment:
  sdk: '^3.10.0'


dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2

  humanizer:
    git:
      url: https://github.com/hiddify/humanizer.git
      ref: main


dependency_overrides:
  intl: 0.20.2
